# Generated by Django 5.0 on 2023-12-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tracker', '0008_alter_movie_date_alter_movie_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='all_time_favorites',
            field=models.ManyToManyField(blank=True, related_name='all_time_favorites', to='movie_tracker.movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recently_viewed_movies',
            field=models.ManyToManyField(blank=True, related_name='recently_viewed_movies', to='movie_tracker.movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='top3_movies',
            field=models.ManyToManyField(blank=True, related_name='top3_movies', to='movie_tracker.movie'),
        ),
    ]
