# Generated by Django 5.0 on 2023-12-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tracker', '0010_rename_social_links_profile_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recently_viewed_movies',
            field=models.ManyToManyField(blank=True, related_name='viewed_by_profiles', to='movie_tracker.movie'),
        ),
    ]
